# Site settings
title: Rahul Iyer's CV 
description: Rahul Iyer's CV (Data Scientist)
favicon: /assets/img/my_pic.jpg
baseurl: 
url: https://rahul-iyer.github.io/
rss_url: /pages/atom.xml
#for seo
gems:
  - jekyll-seo-tag
social:
  name: Rahul Iyer
  links:
    - https://www.facebook.com/rahulniyer
    - https://www.linkedin.com/in/rahulniyer/
    - https://github.com/rahul-iyer

google-site-verification: Abe5GAr5C5co686N8lvz0KXNR5WbHIHu_g9mQdB_eaM

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Rahul Iyer
  title: Data Scientist & Software Developer
  address: Mumbai, India
  email: iyer.rahul100@gmail.com
  #link: http://ddbullfrog.com
  weibo:
  github: rahul-iyer
  linkedin: rahulniyer
  #twitter: ddbullfrog
  gavatar: /resumecard/assets/img/my_pic.jpg
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: News Corp BigDecisions, News Corp VCCircle
      location: Mumbai, India
      title: Data Science Analyst@BigDecisions, Software Engineer@VCCircle
      started: Jul 2016
      duration: (Jul 2016 - Present)
      description: |+
                  1. Here I have migrated the company databases from database from Amazon Redshift to Google BigQuery.<br>
                  2. I am also currently involved in developing state of the art Asset allocation models, which involves use of machine learning in finance data. I have developed income and expense prediction models using various data related to family like family structure, size , dependents etc.<br>
                  3. I have used Big Data handling technologies such as Apache Spark's MLlib to conduct text mining on life insurance claims.<br>
                  4. I have also developed a complete full fledged Database and site search engine using Elastic search and deployed it as an AWS service. Here the data was migrated from Legacy MySQL System to a NoSQL database.<br>
                  5. Made a Restful API Service to fetch data from Elasticsearch which handled all HTTP queries.<br>
                  6. Designed a complete Serverless system of VCCEdge sytem , deployed it in AWS Lambda and authentication using Auth0.
    - work2:
      company: News Corp BigDecisions
      location: Mumbai, India
      title: Data Science Consultant
      started: Aug 2015
      duration: (Aug 2015 - Feb 2016)
      description: |+ 
                  1. I worked as a Consultant contributing to their data advisory platform integrated into Calculators.<br> 
                  2. I have improved the performance of in house analytic dashboard by over 20 times by efficiently caching the data locally.<br>
                  3. I have also clustered users who are beneficial to marketing and reduced the marketing costs by over 5% and improved click to buy performance by 8%.<br>
                  4. I have also classified about a million medical receipts using natural language processing techniques into relavent disease categories.<br>
                  5. I have developed mini tools using Rshiny like Smoking Calculator and eligible bachelor calculator.<br>
    - work3:
      company: Indian Oil Corporation 
      location: Mumabi, India
      title: Software Engineering Intern
      started: Jun 2014
      duration: (Jun 2014 - Jul 2014)
      description: |+
                   1.During my internship at IOCL I built an active news updating feed for users who don’t have any internet access.<br>
                   2.I also helped them setting up their intranet service more efficiently by redesigning the complete interface with bootstrap theme.
    - work4:
      company: Stupidsid.com
      location: Mumabi, India
      title: PHP Developer Intern
      started: Dec 2013
      duration: (Dec 2013 - Jan 2014)
      description: |+
                   1.I added chat feature for profiles to communicate and also tuned the performance of the website.<br>
                   2.I also improved the performance of the grad school recommendation system which is a big hit among the students.
  educationHistory:
    - education1:
      organization: Vivekanand Education Society's Institute of Technology(Uni of Mumbai)
      location: Mumbai, India
      degree: Bachelor of Engineering
      major: Computer Engineering
      started: 2012
      duration: (2012 - 2016)
  projects:
    - project1:
      date: 2016
      research: Y
      title: RecoMob Opinion Mining for Product Enhancement
      description: The primary objective was to understand mobile features like positive and negative aspects of a product from user-provided reviews by determining the sentiment. I used a Deep Recurrent neural network to classify the reviews for which I converted 3000 reviews of top mobile brands from Amazon and Flipkart into sentiment treebank model and used this as my training set. I have consolidated my research into a paper titled RecoMob- Opinion Mining for Product Enhancement in 2017 IEEE International Conference on Computer Communication and Informatics
    - project2:
      date: 2015
      research: Y
      title: English to SQL Machine Transaltion
      description: I used statistical machine translation to convert English sentences (questions/query) into SQL with the help of MOSES and MGIZA++ (Word Aligner) to translate sentences.The system was fed with parallel training text data containing 500 sentences, one in English and the other in SQL having its corresponding translation.
    - project3:
      research: Y
      date: 2014
      title: All Round Student evaluation System
      description: This system was used to track a student’s academic records, extracurricular activities, research and work experience to predict their calibre and determine if they are all round students. The system not only made predictions but also suggested how students could improve their weaknesses.
    - project4:
      date : 2016
      course : Y
      title: Airline delay prediction using Apache Hadoop and R
      description: Wrote a logistic regression model to predict the delay of flight aircraft using various parameters such as weather, flight reroute status, data time, airline carrier name, airport etc using R and Hadoop on 5 million flight details of US and analyzed different patterns of delay.
    - project5:
      date : 2015
      title : SMS spam detection
      course: Y 
      description: Conducted text analytics on SMSs and classified them into spam or ham using Support Vector Machine.
    - project6:
      date: 2014
      title : Virtual Private Network using Raspberry Pi
      course : Y
      description : Wrote a simple shell script to switch to a private network whenever RPi connects to a network using wlan0 interface.
  languages:
    - language1:
      name: Tamil
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Hindi
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: Python
      percentage: 90%
    - skill2:
      name: Java
      percentage: 80%
    - skill3:
      name: R
      percentage: 80%
    - skill4:
      name: C
      percentage: 70%
    - skill5:
      name: HTML and JavaScript
      percentage: 70%
    - skill6:
      name: PHP
      percentage: 60%
  technicalskills:
    - skill1:
      name: Databases
      description: Google BigQuery, MySQL,PostgreSql, NoSQL
    - skill2:
      name: Big Data technologies
      description: Apache Hadoop, Apache Spark, Hive, Spark Dataframes
    - skill3:
      name: Search
      description: Apache Lucene, Elasticsearch
    - skill4:
      name: Deep Learning
      description: Theano, Tensorflow
    - skill5:
      name: Other
      description: Machine Learning, NLP and Specialized Mining Algorithms for Big Data

